"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import {
  PlusCircle,
  Package,
  ClipboardList,
  Upload,
  ImageIcon,
  CheckCircle2,
  XCircle,
  Sparkles,
  RefreshCw,
} from "lucide-react";

// ✅ FIX: productsLocal exports Product, not MartProduct
import { addProduct, getProducts, type Product } from "@/lib/mart/productsLocal";

const AUTH_KEY = "geonest_admin_auth";

function money(n: number) {
  return `GHS ${Number(n || 0).toLocaleString()}`;
}

function slugId(name: string) {
  const s = name
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
  const rand = Math.random().toString(36).slice(2, 6);
  return `p-${s || "product"}-${rand}`;
}

function cleanWords(s: string) {
  return s
    .replace(/\s+/g, " ")
    .replace(/[^\w\s-]/g, "")
    .trim();
}

function titleCase(s: string) {
  return s
    .split(" ")
    .filter(Boolean)
    .map((w) => w[0]?.toUpperCase() + w.slice(1).toLowerCase())
    .join(" ");
}

/** ✅ Local “AI-ish” description generator (no API needed) */
function autoGenerateDescription(opts: {
  name: string;
  category: string;
  badge?: string;
  tags?: string[];
  priceGHS?: number;
}) {
  const name = cleanWords(opts.name);
  const category = cleanWords(opts.category || "store");
  const badge = cleanWords(opts.badge || "");

  const tags = (opts.tags || []).filter(Boolean).slice(0, 4).map(cleanWords);
  const tagLine = tags.length ? `Key features: ${tags.join(", ")}.` : "";

  const vibe =
    badge.toLowerCase().includes("new")
      ? "Fresh pick"
      : badge.toLowerCase().includes("trending")
      ? "Trending choice"
      : badge.toLowerCase().includes("deal")
      ? "Great-value deal"
      : "Solid pick";

  const sentence1 = `${vibe} in ${category}.`;
  const sentence2 = name ? `This ${name} is a reliable option for everyday use.` : "Reliable option for everyday use.";
  const sentence3 =
    opts.priceGHS && opts.priceGHS > 0
      ? `Priced at about GHS ${Number(opts.priceGHS).toLocaleString()}, it’s a smart choice if you want value without stress.`
      : `A smart choice if you want value without stress.`;

  // short + clean
  return [sentence1, sentence2, tagLine, sentence3].filter(Boolean).join(" ");
}

export default function AdminAddNewPage() {
  const router = useRouter();
  const [authed, setAuthed] = useState(false);

  const [toast, setToast] = useState<string | null>(null);

  // form state
  const [name, setName] = useState("");
  const [priceGHS, setPriceGHS] = useState<number>(0);
  const [category, setCategory] = useState("");
  const [customCategory, setCustomCategory] = useState("");
  const [badge, setBadge] = useState("");
  const [tagsText, setTagsText] = useState("");
  const [description, setDescription] = useState("");

  const [imageDataUrl, setImageDataUrl] = useState<string>("");
  const [imgError, setImgError] = useState<string>("");

  function showToast(msg: string) {
    setToast(msg);
    window.clearTimeout((showToast as any)._t);
    (showToast as any)._t = window.setTimeout(() => setToast(null), 2200);
  }

  // ✅ AUTH
  useEffect(() => {
    const ok = sessionStorage.getItem(AUTH_KEY) === "true";
    setAuthed(ok);
    if (!ok) router.replace("/mart/admin");
  }, [router]);

  function logout() {
    sessionStorage.removeItem(AUTH_KEY);
    router.replace("/mart/admin");
  }

  // ✅ get products AFTER mount so window/localStorage is available
  const [existing, setExisting] = useState<Product[]>([]);
  useEffect(() => {
    setExisting(getProducts());

    const onStorage = () => setExisting(getProducts());
    window.addEventListener("storage", onStorage);
    return () => window.removeEventListener("storage", onStorage);
  }, []);

  const categories = useMemo(() => {
    const set = new Set<string>();
    existing.forEach((p: any) => {
      const c = String(p.category ?? p.categorySlug ?? "").trim();
      if (c) set.add(c);
    });
    return Array.from(set).sort((a, b) => a.localeCompare(b));
  }, [existing]);

  // ✅ FIX: if categories load later, set default category
  useEffect(() => {
    if (!category && categories.length) setCategory(categories[0]);
  }, [categories, category]);

  async function onPickFile(file: File | null) {
    setImgError("");
    if (!file) return;

    const maxMB = 1.5; // localStorage safety
    if (file.size > maxMB * 1024 * 1024) {
      setImgError(`Image too large. Keep it under ${maxMB}MB.`);
      return;
    }

    const reader = new FileReader();
    reader.onload = () => {
      const res = String(reader.result || "");
      if (!res.startsWith("data:image/")) {
        setImgError("Please upload an image file.");
        return;
      }
      setImageDataUrl(res);
    };
    reader.onerror = () => setImgError("Could not read the file.");
    reader.readAsDataURL(file);
  }

  function validate() {
    const finalCategory = (customCategory || category).trim();
    if (!name.trim()) return "Product name is required.";
    if (!finalCategory) return "Category is required.";
    if (!priceGHS || priceGHS <= 0) return "Price must be greater than 0.";
    if (!imageDataUrl) return "Please upload a product image.";
    return null;
  }

  function reset() {
    setName("");
    setPriceGHS(0);
    setCategory(categories[0] || "");
    setCustomCategory("");
    setBadge("");
    setTagsText("");
    setDescription("");
    setImageDataUrl("");
    setImgError("");
  }

  function handleAutoDescription() {
    const finalCategory = (customCategory || category).trim();
    const tags = tagsText
      .split(",")
      .map((t) => t.trim())
      .filter(Boolean);

    const generated = autoGenerateDescription({
      name,
      category: finalCategory,
      badge,
      tags,
      priceGHS,
    });

    setDescription(generated);
    showToast("Description generated ✨");
  }

  function submit() {
    const err = validate();
    if (err) {
      showToast(err);
      return;
    }

    const finalCategory = (customCategory || category).trim();
    const tags = tagsText
      .split(",")
      .map((t) => t.trim())
      .filter(Boolean);

    const p: Product = {
      id: slugId(name),
      name: name.trim(),
      priceGHS: Number(priceGHS),
      // supports both shapes
      category: finalCategory as any,
      image: imageDataUrl,
      badge: (badge.trim() as any) || undefined,

      tags: tags.length ? tags : undefined,
      description: description.trim() || undefined,
      createdAt: new Date().toISOString(),
    };

    try {
      addProduct(p);
      showToast("Product added ✅");
      router.push("/mart/admin/products");
    } catch (e: any) {
      showToast(e?.message || "Could not add product.");
    }
  }

  if (!authed) {
    return (
      <div className="min-h-[70vh] flex items-center justify-center px-4">
        <div className="w-full max-w-sm rounded-[28px] bg-white p-6 ring-1 ring-neutral-200/70">
          <p className="text-sm font-medium">Admin session required</p>
          <p className="mt-1 text-sm text-neutral-600">Redirecting…</p>
          <div className="mt-5 h-2 w-full overflow-hidden rounded-full bg-neutral-100">
            <div className="h-full w-1/2 animate-pulse rounded-full bg-red-600/30" />
          </div>
        </div>
      </div>
    );
  }

  const finalCategory = (customCategory || category).trim();
  const previewTags = tagsText
    .split(",")
    .map((t) => t.trim())
    .filter(Boolean)
    .slice(0, 8);

  return (
    <div className="py-10">
      <div className="mx-auto max-w-6xl px-4">
        {toast && (
          <div className="mb-4 rounded-xl bg-neutral-900 px-4 py-2 text-xs text-white">
            {toast}
          </div>
        )}

        {/* Header */}
        <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
          <div>
            <p className="text-xs uppercase tracking-[0.25em] text-neutral-500">
              Geonest Mart
            </p>
            <h1 className="mt-2 text-2xl font-semibold">Admin · Add New</h1>
            <p className="mt-1 text-sm text-neutral-600">
              Upload a product with image — it will show in the shop.
            </p>
          </div>

          {/* Mini nav */}
          <div className="flex flex-wrap gap-2">
            <Link
              href="/mart/admin/orders"
              className="inline-flex items-center gap-2 rounded-full bg-white px-4 py-2 text-sm ring-1 ring-neutral-200/70 hover:bg-neutral-50"
            >
              <ClipboardList className="h-4 w-4" />
              Orders
            </Link>
            <Link
              href="/mart/admin/products"
              className="inline-flex items-center gap-2 rounded-full bg-white px-4 py-2 text-sm ring-1 ring-neutral-200/70 hover:bg-neutral-50"
            >
              <Package className="h-4 w-4" />
              Products
            </Link>
            <Link
              href="/mart/admin/new"
              className="inline-flex items-center gap-2 rounded-full bg-red-600 px-4 py-2 text-sm text-white hover:bg-red-700"
            >
              <PlusCircle className="h-4 w-4" />
              Add New
            </Link>
            <button
              onClick={logout}
              className="inline-flex items-center gap-2 rounded-full bg-white px-4 py-2 text-sm ring-1 ring-neutral-200/70 hover:bg-neutral-50"
            >
              <XCircle className="h-4 w-4" />
              Logout
            </button>
          </div>
        </div>

        {/* Content */}
        <div className="mt-6 grid gap-6 lg:grid-cols-[1.1fr_0.9fr]">
          {/* Form */}
          <div className="rounded-[28px] bg-white p-6 ring-1 ring-neutral-200/70">
            <div className="grid gap-4 sm:grid-cols-2">
              <div className="sm:col-span-2">
                <label className="text-sm font-medium text-neutral-700">
                  Product name
                </label>
                <input
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                  className="mt-2 h-11 w-full rounded-2xl bg-neutral-50 px-3 text-sm ring-1 ring-neutral-200 focus:outline-none focus:ring-2 focus:ring-red-500/30"
                  placeholder="e.g. Wireless Earbuds Pro"
                />
              </div>

              <div>
                <label className="text-sm font-medium text-neutral-700">
                  Price (GHS)
                </label>
                <input
                  value={priceGHS || ""}
                  onChange={(e) => setPriceGHS(Number(e.target.value))}
                  type="number"
                  className="mt-2 h-11 w-full rounded-2xl bg-neutral-50 px-3 text-sm ring-1 ring-neutral-200 focus:outline-none focus:ring-2 focus:ring-red-500/30"
                  placeholder="e.g. 399"
                />
              </div>

              <div>
                <label className="text-sm font-medium text-neutral-700">
                  Badge (optional)
                </label>
                <input
                  value={badge}
                  onChange={(e) => setBadge(e.target.value)}
                  className="mt-2 h-11 w-full rounded-2xl bg-neutral-50 px-3 text-sm ring-1 ring-neutral-200 focus:outline-none focus:ring-2 focus:ring-red-500/30"
                  placeholder="New / Trending / Deal"
                />
              </div>

              <div>
                <label className="text-sm font-medium text-neutral-700">
                  Category
                </label>
                <select
                  value={category}
                  onChange={(e) => setCategory(e.target.value)}
                  className="mt-2 h-11 w-full rounded-2xl bg-neutral-50 px-3 text-sm ring-1 ring-neutral-200 focus:outline-none focus:ring-2 focus:ring-red-500/30"
                >
                  {categories.length === 0 ? (
                    <option value="">No categories yet</option>
                  ) : (
                    categories.map((c) => (
                      <option key={c} value={c}>
                        {titleCase(c)}
                      </option>
                    ))
                  )}
                </select>
                <p className="mt-1 text-xs text-neutral-500">
                  Or type a new one below.
                </p>
              </div>

              <div>
                <label className="text-sm font-medium text-neutral-700">
                  Custom category (optional)
                </label>
                <input
                  value={customCategory}
                  onChange={(e) => setCustomCategory(e.target.value)}
                  className="mt-2 h-11 w-full rounded-2xl bg-neutral-50 px-3 text-sm ring-1 ring-neutral-200 focus:outline-none focus:ring-2 focus:ring-red-500/30"
                  placeholder="e.g. accessories"
                />
              </div>

              <div className="sm:col-span-2">
                <label className="text-sm font-medium text-neutral-700">
                  Tags (comma separated, optional)
                </label>
                <input
                  value={tagsText}
                  onChange={(e) => setTagsText(e.target.value)}
                  className="mt-2 h-11 w-full rounded-2xl bg-neutral-50 px-3 text-sm ring-1 ring-neutral-200 focus:outline-none focus:ring-2 focus:ring-red-500/30"
                  placeholder="e.g. bluetooth, student, fast-charging"
                />
              </div>

              <div className="sm:col-span-2">
                <div className="flex items-center justify-between gap-3">
                  <label className="text-sm font-medium text-neutral-700">
                    Description (optional)
                  </label>

                  {/* ✅ AUTO GENERATE */}
                  <button
                    type="button"
                    onClick={handleAutoDescription}
                    className="inline-flex items-center gap-2 rounded-full bg-neutral-100 px-4 py-2 text-xs hover:bg-neutral-200 transition"
                  >
                    <Sparkles className="h-4 w-4" />
                    Auto-generate
                  </button>
                </div>

                <textarea
                  value={description}
                  onChange={(e) => setDescription(e.target.value)}
                  className="mt-2 min-h-[110px] w-full rounded-2xl bg-neutral-50 px-3 py-3 text-sm ring-1 ring-neutral-200 focus:outline-none focus:ring-2 focus:ring-red-500/30"
                  placeholder="Short description that can show on product page later."
                />
              </div>

              {/* Image uploader */}
              <div className="sm:col-span-2">
                <label className="text-sm font-medium text-neutral-700">
                  Product image
                </label>

                <div className="mt-2 rounded-2xl border border-dashed border-neutral-300 bg-neutral-50 p-4">
                  <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
                    <div className="flex items-center gap-2 text-sm text-neutral-700">
                      <Upload className="h-4 w-4" />
                      Upload an image (max ~1.5MB)
                    </div>

                    <label className="inline-flex cursor-pointer items-center gap-2 rounded-2xl bg-neutral-900 px-4 py-2 text-sm text-white hover:bg-neutral-800">
                      <ImageIcon className="h-4 w-4" />
                      Choose file
                      <input
                        type="file"
                        accept="image/*"
                        className="hidden"
                        onChange={(e) => onPickFile(e.target.files?.[0] || null)}
                      />
                    </label>
                  </div>

                  {imgError ? (
                    <p className="mt-2 text-sm text-red-600">{imgError}</p>
                  ) : null}

                  {imageDataUrl ? (
                    <div className="mt-4 overflow-hidden rounded-2xl ring-1 ring-neutral-200">
                      <img
                        src={imageDataUrl}
                        alt="Preview"
                        className="h-56 w-full object-cover"
                      />
                    </div>
                  ) : (
                    <p className="mt-3 text-xs text-neutral-500">
                      No image selected yet.
                    </p>
                  )}
                </div>
              </div>
            </div>

            <div className="mt-6 flex flex-wrap gap-2">
              <button
                onClick={submit}
                className="inline-flex items-center gap-2 rounded-2xl bg-red-600 px-5 py-3 text-sm font-medium text-white hover:bg-red-700"
              >
                <CheckCircle2 className="h-4 w-4" />
                Add product
              </button>

              <button
                onClick={reset}
                className="inline-flex items-center gap-2 rounded-2xl bg-white px-5 py-3 text-sm ring-1 ring-neutral-200 hover:bg-neutral-50"
              >
                <RefreshCw className="h-4 w-4" />
                Clear
              </button>
            </div>
          </div>

          {/* Preview */}
          <div className="rounded-[28px] bg-white p-6 ring-1 ring-neutral-200/70">
            <p className="text-xs uppercase tracking-[0.25em] text-neutral-500">
              Preview
            </p>

            <div className="mt-4 overflow-hidden rounded-[22px] ring-1 ring-neutral-200">
              {imageDataUrl ? (
                <img src={imageDataUrl} alt="Preview" className="h-56 w-full object-cover" />
              ) : (
                <div className="flex h-56 items-center justify-center bg-neutral-50 text-sm text-neutral-500">
                  Image preview
                </div>
              )}
            </div>

            <div className="mt-4">
              <p className="text-sm font-semibold">{name || "Product name"}</p>
              <p className="mt-1 text-sm text-neutral-600">
                {priceGHS ? money(priceGHS) : "GHS 0"}
              </p>

              <div className="mt-3 flex flex-wrap gap-2">
                <span className="rounded-full bg-neutral-100 px-3 py-1 text-xs text-neutral-700">
                  {finalCategory || "category"}
                </span>
                {badge.trim() ? (
                  <span className="rounded-full bg-red-600 px-3 py-1 text-xs text-white">
                    {badge.trim()}
                  </span>
                ) : null}
              </div>

              {previewTags.length ? (
                <p className="mt-3 text-xs text-neutral-500">
                  Tags: {previewTags.join(" · ")}
                </p>
              ) : null}

              {description.trim() ? (
                <p className="mt-3 text-sm text-neutral-600">{description.trim()}</p>
              ) : (
                <p className="mt-3 text-sm text-neutral-500">
                  Tap <b>Auto-generate</b> to create a description.
                </p>
              )}
            </div>

            <p className="mt-6 text-xs text-neutral-500">
              Note: images are saved in localStorage for now (great for demo). Later we can
              switch to real uploads (Cloudinary/Firebase/S3) without changing the UI much.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
